--
- name: Install metric beat
  hosts: elk
  become: true
  tasks:
  - name: Get Metricbeat
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb
	
  - name: Install Metricbeat
    command: dpkg -i metricbeat-7.6.1-amd64.deb
	
  - name: Copy Reference Metricbeat YAML
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml
	  
  - name: Enable metricbeat for Docker
    command: metricbeat modules enable docker
	
  - name: Execute Metricbeat Setup
    command: metricbeat setup

  - name: Start Metricbeat
    command: sudo service metricbeat start
